# Katzenpost server configuration file.

#
# The Server section contains mandatory information common to all nodes.
#

[Server]
  Identifier = "provider2"

  # Addresses are the IP address/port combinations that the server will bind
  # to for incoming connections.
  Addresses = [ "172.28.1.4:29484"]

  # DataDir is the absolute path to the server's state files.
  DataDir = "/conf/provider_data"

  # IsProvider specifies if the server is a provider (vs a mix).
  IsProvider = true

#
# The PKI section contains the directory authority configuration.
#

[PKI]
  [PKI.Voting]
  [[PKI.Voting.Peers]]
    Addresses = ["172.28.1.10:21483"]
    IdentityPublicKey = "xCjlBac+wanLeUQbrNLTwQzFKIwfJqpoKZYfB/hvZHo="
    LinkPublicKeyPem = "auth1_link_pub_key.pem"

  [[PKI.Voting.Peers]]
    Addresses = ["172.28.1.8:22483"]
    IdentityPublicKey = "OAfHeF/U+y7dXWgxSCuPOBIqgBOuIC7JKilZJU/Dt9c="
    LinkPublicKeyPem = "auth2_link_pub_key.pem"

  [[PKI.Voting.Peers]]
    Addresses = ["172.28.1.9:23483"]
    IdentityPublicKey = "e8iJCBjepa/Cpmmu5UCcR6BZgYssUTaih9U01ysEK+o="
    LinkPublicKeyPem = "auth3_link_pub_key.pem"


#
# The Logging section controls the logging.
#

[Logging]

  # Disable disables logging entirely.
  Disable = false

  # File specifies the log file, if omitted stdout will be used.
  File = "/conf/provider_data/katzenpost.log"

  # Level specifies the log level out of `ERROR`, `WARNING`, `NOTICE`,
  # `INFO` and `DEBUG`.
  #
  # Warning: The `DEBUG` log level is unsafe for production use.
  Level = "DEBUG"

[Debug]
  DisableRateLimit = true

#
# The Provider secton specifies the Provider configuration.
#

[Provider]

  [[Provider.Kaetzchen]]
    Capability = "echo"
    Endpoint = "+echo"
    Disable = false

  [[Provider.CBORPluginKaetzchen]]
    Capability = "reunion"
    Endpoint = "+reunion"
    Command = "/go/bin/reunion_katzenpost_server"
    MaxConcurrency = 1
    [Provider.CBORPluginKaetzchen.Config]
      log_level = "DEBUG"
      log = "/conf/service_logs/reunion.log"
      s = "/conf/service_data/reunion.storage"
#
# The Management section specifies the management interface configuration.
#

[Management]

  # Enable enables the management interface.
  Enable = true

  # Path specifies the path to the management interface socket.  If left
  # empty it will use `management_sock` under the DataDir.
  Path = "/conf/provider_data/management_sock"
