image: "golang:1.11"

before_script:
  - mkdir -p /go/src/github.com
  - cp -r /builds/katzenpost /go/src/github.com/katzenpost/
  - cd /go/src/github.com/katzenpost/authority
  - go get -v -t ./...

test-authority:
  script:
    - go test -v -cover -race ./internal/...
    - go test -cover -v -race ./voting/...
    - go test -cover -v -race ./nonvoting/...
