image: "golang:1.11"

before_script:
  - mkdir -p /go/src/github.com
  - cp -r /builds/katzenpost /go/src/github.com/katzenpost/
  - cd /go/src/github.com/katzenpost/client
  - go get -v -t ./...

test-client:
  script:
    - go test -v -cover -race -timeout 0 -ldflags "-X github.com/katzenpost/core/epochtime.WarpedEpoch=true -X github.com/katzenpost/server/internal/pki.WarpedEpoch=true" ./...
