image: "golang:1.13"

before_script:
  - mkdir -p /go/src/github.com/katzenpost
  - cp -r /builds/katzenpost/* /go/src/github.com/katzenpost/
  - cd /go/src/github.com/katzenpost/authority
  - go get -v -t ./...

test-authority:
  script:
    - go test -cover -v -race ./internal/...
    - go test -cover -v -race ./voting/...
    - go test -cover -v -race ./nonvoting/...
    - go test -cover -v -race -timeout 0 -ldflags "-X github.com/katzenpost/core/epochtime.WarpedEpoch=true -X github.com/katzenpost/server/internal/pki.WarpedEpoch=true" ./tests/...
