image: "golang:1.11"

before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - cp -r /builds/katzenpost /go/src/github.com/katzenpost/
  - cd /go/src/github.com/katzenpost/client
  - dep ensure -v

test-client:
  script:
    - go test -v -cover -race -timeout 0 -ldflags "-X github.com/katzenpost/client/vendor/github.com/katzenpost/core/epochtime.WarpedEpoch=true -X github.com/katzenpost/client/vendor/github.com/katzenpost/server/internal/pki.WarpedEpoch=true" ./...
