# Copyright (C) 2020  David Stainton.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
project_name: catshadow
sign:
   artifacts: checksum
builds:
  # multiple builds defined as a yaml list
  -
    main: ./cmd/
    binary: catshadow
    flags: |
        -tags netgo -gcflags="-trimpath=$GOPATH" -asmflags="-trimpath=$GOPATH"
    env:
      - CGO_ENABLED=0
    ldflags: |
      -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -extldflags '-static'
    goos:
      - linux
      - freebsd
      - netbsd
      - openbsd
      - darwin
    goarch:
      - arm64
      - amd64
archive:
  name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
  format: tar.gz
  wrap_in_directory: true
  files:
    - LICENSE
nfpm:
  vendor: Katzenpost Authors
  homepage: "https://katzenpost.mixnetworks.org/"
  maintainer: "irc://irc.oftc.net/#katzenpost"
  license: AGPL
  formats:
    - deb
    - rpm
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
release:
  github:
    owner: katzenpost
    name: catshadow
  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false

  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: true

  # You can change the name of the GitHub release.
  # Default is ``
  #  name_template: "{{.ProjectName}}-v{{.Version}}-{{.Os}}-{{.Arch}}"

  # You can disable this pipe in order to not upload any artifacts to
  # GitHub.
  # Defaults to false.
  disable: false