language: go

go:
  - "1.13"

env:
  global:
    GO111MODULE=on

install:
  - git config --global http.https://gopkg.in.followRedirects true
  - go get -v -t ./...

script:
  - go test -cover -v -race ./internal/...
  - go test -cover -v -race ./voting/...
  - go test -cover -v -race ./nonvoting/...
