language: go

go:
  - "1.12"

env:
  global:
    GO111MODULE=on

install:
  - git config --global http.https://gopkg.in.followRedirects true
  - go get -v -t ./...

script:
 - make test-internal
 - make test-voting
 - make test-nonvoting
