language: go

go:
  - "1.10"
  - "1.11"

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -v

script:
  - go test -v -cover -race -timeout 0 -ldflags "-X github.com/katzenpost/client/vendor/github.com/katzenpost/core/epochtime.WarpedEpoch=true -X github.com/katzenpost/client/vendor/github.com/katzenpost/server/internal/pki.WarpedEpoch=true" ./...
