version: "2"

services:
  provider1:
    restart: unless-stopped
    image: katzenpost/server
    volumes:
      - ./conf/provider1:/conf
    command: /go/bin/server -f /conf/katzenpost.toml
    ports:
      - 59484:59484
    depends_on:
      - auth
    networks:
      testing_net:
        ipv4_address: 172.28.1.3

  provider2:
    restart: unless-stopped
    image: katzenpost/server
    volumes:
      - ./conf/provider2:/conf
    command: /go/bin/server -f /conf/katzenpost.toml
    ports:
      - 29484:29484
      - 8060:8080
    depends_on:
      - auth
      - provider1
    networks:
      testing_net:
        ipv4_address: 172.28.1.4

  auth:
    restart: unless-stopped
    image: katzenpost/authority
    volumes:
      - ./conf/auth:/conf
    command: /go/bin/nonvoting -f /conf/authority.toml
    ports:
      - 29483:29483
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
