# Katzenpost non-voting authority configuration file.

#
# The Authority section contains mandatory information.
#

[Authority]

  # Addresses are the IP address/port combinations that the authority will bind
  # to for incoming connections.
  Addresses = [ "172.28.1.10:21483" ]

  # DataDir is the absolute path to the server's state files.
  DataDir = "/conf/authority_data"

#[[Authorities]]
#   IdentityPublicKey = "xCjlBac+wanLeUQbrNLTwQzFKIwfJqpoKZYfB/hvZHo="
#   LinkPublicKey = "I49V1w7OJ/Kcw7YbEvo+92akE9cYLGeXRBg6KE/sYS8="
#   Addresses = [ "172.28.1.10:21483" ]

[[Authorities]]
   IdentityPublicKey = "OAfHeF/U+y7dXWgxSCuPOBIqgBOuIC7JKilZJU/Dt9c="
   LinkPublicKey = "fZcGD+uPm18BYuDKXS3eozp9+i2hW2SWgnuapP0ftgE="
   Addresses = [ "172.28.1.8:22483" ]

[[Authorities]]
   IdentityPublicKey = "e8iJCBjepa/Cpmmu5UCcR6BZgYssUTaih9U01ysEK+o="
   LinkPublicKey = "jBVovebgazZB38Q3OZzEvLb8UDEUB6sRQZAULDrxKAY="
   Addresses = [ "172.28.1.9:23483" ]

#
# The Logging section controls the logging.
#

[Logging]

  # Disable disables logging entirely.
  Disable = false

  # File specifies the log file, if omitted stdout will be used.
  File = "/conf/authority_data/katzenpost.log"

  # Level specifies the log level out of `ERROR`, `WARNING`, `NOTICE`,
  # `INFO` and `DEBUG`.
  #
  # Warning: The `DEBUG` log level is unsafe for production use.
  Level = "DEBUG"


[Debug]
  MinNodesPerLayer = 1

#
# The Parameters section holds the network parameters.
#

[Parameters]
  SendRatePerMinute = 0
  Mu = 0.001
  MuMaxDelay = 9000
  LambdaP = 0.002
  LambdaPMaxDelay = 10000
  LambdaL = 0.0005
  LambdaLMaxDelay = 10000
  LambdaD = 0.0005
  LambdaDMaxDelay = 30000
  LambdaM = 0.2
  LambdaMMaxDelay = 100

#
# The Mixes array defines the list of white-listed non-provider nodes.
#

[[Mixes]]
  # mix1
  IdentityKey = "4r9jePAbuzhytcnM3nbD5UQOmzl1X1hI8QOMbhTrg8s="

[[Mixes]]
  # mix2
  IdentityKey = "1x8tq04hY+i83o9Yn2nrfTkFj4jXIMWCWilR7fgrWyM="

[[Mixes]]
  # mix3
  IdentityKey = "La2FnsbKoU8dzQhfN4zkxSYn6T7LRWmFn0JgtlEklQw="

#
# The Providers array defines the list of white-listed Provider nodes.
#

[[Providers]]
  Identifier = "provider2"
  IdentityKey = "imigzI26tTRXyYLXujLEPI9QrNYOEgC4DElsFdP9acQ="

[[Providers]]
  Identifier = "provider1"
  IdentityKey = "2krwfNDfbakZCSTUUZYKXwdduzlEgS9Jfwm7eyZ0sCg="

