[Server]
  Identifier = "auth1"
  Addresses = ["127.0.0.1:30001"]
  DataDir = "/conf/auth1"

[[Authorities]]
  Identifier = "auth3"
  IdentityPublicKey = "-----BEGIN ED25519 SPHINCS+ PUBLIC KEY-----\n77xBqyu4uw4/OuX7d8zWbv9XmF6R2MXSibbYZkUUvT1WHaPgLP0Hd23qwr7ilwgW\nccIAREfio6PFzZp392G85vavD7IWm0zmNJmjGM/2shQbT+NLKyDCIaelYKeZ+bPd\n-----END ED25519 SPHINCS+ PUBLIC KEY-----\n"
  LinkPublicKey = "-----BEGIN KYBER768-X25519 PUBLIC KEY-----\nd1Mua2snAwfFTKRcWyhZfs+87GEYB+/KTdlaFbLHf15FDIZJamnDdkPBvBrCFwy6\nBwvXyYBkkwRBVjrYGowg5H/CmhBepqV+Ah+Pp0iUc3xcskQlmjVkILCgaAVgcF6p\nCaDMiV6y5bJ71JrEAYiVs42INaQoJ1KdtZwLd2R/GVu/a50rgYPFnEX/FGd6WXlp\nMmROOj8AYEXzyxfOFkM4PDKH6nKocAuPNCxquiy4q6o5gBYRmG1NjJw38ZP5tQJ7\n8XFLewCc0BX7S3TiukLTRx4K8X3+1os450MlAB7jQL+F7CSu7KgwB3jk8Fam9QtK\n+LNX+D4hXAlpCyesu3+KNRXoFWHpHHT9cYW8OEN4E46ApqmyIZ5HC7IbK4pS/FtA\npglxa5XPSm06yGw3FzKeEYgNYy731gSQZLfAvMhau67l45gsSi9W/KnnhlfLZoqa\nIR/4x3V5kc/kDFiOY5DyHJfiUDnpsLmJKc06UGX2E4sHIsyUh3i/kzjkAiIlNqly\ngK0F2WuCkoCH67A8bFvlnCPSRYm7l1705kmOM5G6HMBlagL+9sxdeap3XHaLUjdm\nM7KfZhlTcXuLLJtsPMXbpVGrqho4zFPDtWAQM7oOki1Dkpz9qANTaU9Y2g4e9qvQ\nHMypJIDxFxOfljEmmQMY+1fBUwq2Qa6WWUKD62StqLEEgUB0eVSBPHULil4N0Ymc\nWbcOlh3+dionG63dyUpFSXNHy2dx1ZRyucNADAKB2XfTMlPWqg4DCEA6Qgfq66N+\ngLcHgEhHkLPdtASrEYNJQ61krECMGanVthSUkZG64av++SDCkDCrI5Wls2Bf7HLg\no8TfvK+Q8Dk4IYrZYDNhGm3wNseiuMQPiW0n0BdlaznKyYBhUD77w0AtaAztcXSk\naSMK+62H8a7eDK48os1C2atdGSiKIQLY2ZzPwThR5VClaW5oVafe7Dhx6BGht7io\nfGsMJBPQel5SPLcqexHdAax7EAOid2SFgniMhpcvIrDw9ZoLeUwDQltMGkI76p7F\nV7aOak2T9cZLcxE+SwSVAnR6hB3RPA07yZCS8hC+K5BFU3fGhiJe1JI/UlRqgWeS\nSlorUojrRY47qVAjqqf2jG4PBLtV5Zv/O7bXEWyBSoJY+AR53BXStVTeZravt3L6\nw6F1lYIL+zof5i0XsRRBk8oIFzKTsyCMVHYEEH9hNMZmrD7mArtyoFX7+XWK9Vns\nEXBh7EiomVScuDljGYUEd2CHywxJKWWFxXerB3ZvohkoAgSS25lBN6w0Cp7eVl+X\na5UJNW4ShIVcXEjlA0xDy7AMpXn0J49CkXfxNmvSI8VmsDQ6yiq3i8kJtLxVsJRe\ngz/D653p5ClMObx7K1Mi4xIh5DoIy4QNEpmYjE/rXAAiRpOMWnDvWWA2wiUywS1y\nBljRlsa7Vz/2ikVMulSUgCEIaJ3HCGwyIZkLJD6MwIDOtcpjUIHlOyY0wSsVGcLE\nF1jI6EeVxbQt9440s4y3oUsDwGq5sl4lUr6VFoMsobixwpM/LDpDd2UpikGEsJ7h\ngJFF54Tqs4idmra1qwLGqmWjMYl98mtvJ4w/UBaYFR3n0P/ROhNHAgUyW1KLN2pY\n6R+zDiFFlDv4mflmoThiTA==\n-----END KYBER768-X25519 PUBLIC KEY-----\n"
  Addresses = ["127.0.0.1:30003"]

[[Authorities]]
  Identifier = "auth2"
  IdentityPublicKey = "-----BEGIN ED25519 SPHINCS+ PUBLIC KEY-----\nTNlDXHgp8HoMKOiWl++TnZlulG3pPAg3wqQJODa0qxoOiFXBD66yxFS7j3vQDdbx\nmIvTuaMSlIik5/lt8JFx2aVo3dylp3xNkCVlvkCEf5qrHqAIHIADJA2pK7liGH5V\n-----END ED25519 SPHINCS+ PUBLIC KEY-----\n"
  LinkPublicKey = "-----BEGIN KYBER768-X25519 PUBLIC KEY-----\nydAu/lpdD6rbj6vneJwNpQ4pTBMEs863OE5t4YJ/bWdyZzVvmMP14ASIUJ0BlGin\nXMlL14gMDAMzixEAIBx96JVnCH6zNHVufGzjU1rzW51+NGTeXKKyhFe70apVFsQq\nm3uyAyMGBK74uzhiRsq/BZuIeMYRskbzQ0V/kreDGhSol5vNRQ6lqBTNyHVi0G3j\nVS/U27MNJGzymwj69M2X0YZGhLw3S3AyAL6D1rynUYlNKTIxlkHBVRco8WTZ1DCY\nY4I+d2wO5LaiqiN8mU10R6s+MBk0l6Vhc84eNc0+qQTFI8maxZmK25qVdpKKAn7D\nWmTUJW9pdHRIFV+fpEXz1SHl4a9uRyDL3DlB5blmhbrh4Gdn9snDZ5K+Fwtv8T71\n58hU2CHjMng6RMzZ9KoEqrQvSQxg1Z08cJXw0FRn1KE4+ETxSn3JcE+VM5h9ME3/\n0w8ihE3BkU3EJyE6Qc+t+1bYswUrB4RTs1JiwQwImUTjQHkNCTxeTGnNCSz9m1He\nmqC37AOrhT1woYa6uackAg45YSJUe4cSCMuIsYUDRZQE1R+AMCpy1KmazD5L1KZh\n8W/YpKK9VQbB/BjfRXVk+SDaMQ9csjhnGgu6iw9k7LoLACIYOJoB+JlPmgHq2J5Z\n+Casg6TfdAC8mXdOxI3TgYG7pmAxo3rUJsgc1YF6ApiTOFKcrDR66HPiQBbf2TJm\nYQYbsZsuNz2WEsVFDK8PXEi/O1UOsY1/JQoHVx5xiIaBI11eEYnlGcO14MguG6Iq\nM0fGJg6TI7b7Vk2b27LZ5kYS0bhzooVei4JU+LYuRii6Uhr5l4vrOKc362RpZjx9\nobwti7mPRrnfVoa0MLjsZWe2cXxtt5qi6VM/WROE1rfJ5lpk+cx3hqTCK2iM2qYa\nuZiTic3+4wwBCEykB6P597ptZEInY2T4VLod0mCHIx40wi2CELG3hrSlCj94FA8Z\nMM5XwL7hhsPpDKPsuHIUMRyBGMav8gCYZhpuMsYoNQLoJccqeMpqCw8AjQSTEbXv\nw5LSt80Ch4dbpJiywhCB+ceW6LkMcm0XkZZe6yaeWLe8NrgXUXaIo5u8YmTp+qlJ\nwMqmBEbsVUqF1Wv+gpTbKygdkxbZAh2xuwv84smIAjf2KQdA7GBZZUED1jpgAw8J\nEEI7GFK+9qA3o2wuZQUDwnwK6GcMagn88wIKGmwVAj0okE2nZKsymScsE01dNyjd\nZ27FdDzuRjYi2K9nMLg8cX1fEyD+eh/UZLWn11hZ0xZd1zVpC8Hk9rT1VRTA1o4M\n2q1HMlyu9TAB86wyCRzoFXXo5EGPQRV/d4vkw1mPEFix+hxjN3feUhwC+zN7CW7e\noqvb5osYOIRCcpXP8Uh816Qj/GkhqSlQUTiNaq5KFScm404Gmo70/JEGtxy0K4bU\n5QA95glf/Jg+RVCumxw3WgfiE4MgORppC55w5o8sHLwecFGKOsiyHKGRVrpkpcjV\npDnyAXpHw72PKqklpggA5ZBURXXlnBnrRUR3VZGcl4pnQZE+wEquAa+LWn7YBii8\noUEge8Pn3K8d0jj52Jl44hoBYKNZgFnbkJ8ms6L2spuVF0fW+M3b+KjuLpejOvVG\njqVfL9Mga0s+IIWFvQx/LQ==\n-----END KYBER768-X25519 PUBLIC KEY-----\n"
  Addresses = ["127.0.0.1:30002"]

[Logging]
  Disable = false
  File = "katzenpost.log"
  Level = "DEBUG"

[Parameters]
  SendRatePerMinute = 0
  Mu = 0.0
  MuMaxDelay = 0
  LambdaP = 0.0
  LambdaPMaxDelay = 0
  LambdaL = 0.0
  LambdaLMaxDelay = 0
  LambdaD = 0.0
  LambdaDMaxDelay = 0
  LambdaM = 0.0
  LambdaMMaxDelay = 0

[Debug]
  Layers = 3
  MinNodesPerLayer = 1
  GenerateOnly = false

[[Mixes]]
  Identifier = ""
  IdentityPublicKeyPem = "../mix1/identity.public.pem"

[[Mixes]]
  Identifier = ""
  IdentityPublicKeyPem = "../mix2/identity.public.pem"

[[Mixes]]
  Identifier = ""
  IdentityPublicKeyPem = "../mix3/identity.public.pem"

[[Mixes]]
  Identifier = ""
  IdentityPublicKeyPem = "../mix4/identity.public.pem"

[[Mixes]]
  Identifier = ""
  IdentityPublicKeyPem = "../mix5/identity.public.pem"

[[Mixes]]
  Identifier = ""
  IdentityPublicKeyPem = "../mix6/identity.public.pem"

[[Providers]]
  Identifier = "provider1"
  IdentityPublicKeyPem = "../provider1/identity.public.pem"

[[Providers]]
  Identifier = "provider2"
  IdentityPublicKeyPem = "../provider2/identity.public.pem"
