
[UpstreamProxy]
  Type = "none"

[Logging]
  Disable = false
  Level = "DEBUG"
  File = ""

[VotingAuthority]
    [[VotingAuthority.Peers]]
      Addresses = ["127.0.0.1:21483"]
      LinkPublicKeyPem = "auth1_link_pub_key.pem"
      IdentityPublicKeyPem = "auth1_id_pub_key.pem"

    [[VotingAuthority.Peers]]
      Addresses = ["127.0.0.1:22483"]
      LinkPublicKeyPem = "auth2_link_pub_key.pem"
      IdentityPublicKeyPem = "auth2_id_pub_key.pem"

    [[VotingAuthority.Peers]]
      Addresses = ["127.0.0.1:23483"]
      LinkPublicKeyPem = "auth3_link_pub_key.pem"
      IdentityPublicKeyPem = "auth3_id_pub_key.pem"

[Debug]
  DisableDecoyTraffic = true
  PollingInterval = 50
