
[UpstreamProxy]
  Type = "none"

[Logging]
  Disable = false
  Level = "DEBUG"
  File = ""

[ClientLogging]
  Disable = false
  Level = "NOTICE"
  File = ""

[VotingAuthority]
    [[VotingAuthority.Peers]]
      Addresses = ["127.0.0.1:21483"]
      LinkPublicKeyPem = "auth1_link_pub_key.pem"
      IdentityPublicKey = "xCjlBac+wanLeUQbrNLTwQzFKIwfJqpoKZYfB/hvZHo="

    [[VotingAuthority.Peers]]
      Addresses = ["127.0.0.1:22483"]
      LinkPublicKeyPem = "auth2_link_pub_key.pem"
      IdentityPublicKey = "OAfHeF/U+y7dXWgxSCuPOBIqgBOuIC7JKilZJU/Dt9c="

    [[VotingAuthority.Peers]]
      Addresses = ["127.0.0.1:23483"]
      LinkPublicKeyPem = "auth3_link_pub_key.pem"
      IdentityPublicKey = "e8iJCBjepa/Cpmmu5UCcR6BZgYssUTaih9U01ysEK+o="

[Debug]
  DisableDecoyTraffic = true
  CaseSensitiveUserIdentifiers = false
  PollingInterval = 50

[Panda]
  Receiver = "+panda"
  Provider = "provider1"
  BlobSize = 1000

[Reunion]
   Enable = false
