version: "2"

services:
  provider1:
    restart: unless-stopped
    image: katzenpost/server
    volumes:
      - ./conf/provider1:/conf
    command: /go/bin/server -f /conf/katzenpost.toml
    network_mode: host

    depends_on:
      - auth1
      - auth2
      - auth3

  provider2:
    restart: unless-stopped
    image: katzenpost/server
    volumes:
      - ./conf/provider2:/conf
    command: /go/bin/server -f /conf/katzenpost.toml
    network_mode: host
    depends_on:
      - auth1
      - auth2
      - auth3
      - provider1

  mix1:
    restart: unless-stopped
    image: katzenpost/server
    volumes:
      - ./conf/mix1:/conf
    command: /go/bin/server -f /conf/katzenpost.toml
    network_mode: host
    depends_on:
      - auth1
      - auth2
      - auth3
      - provider1
      - provider2

  mix2:
    restart: unless-stopped
    image: katzenpost/server
    volumes:
      - ./conf/mix2:/conf
    command: /go/bin/server -f /conf/katzenpost.toml
    network_mode: host
    depends_on:
      - auth1
      - auth2
      - auth3
      - provider1
      - provider2

  mix3:
    restart: unless-stopped
    image: katzenpost/server
    volumes:
      - ./conf/mix3:/conf
    command: /go/bin/server -f /conf/katzenpost.toml
    network_mode: host
    depends_on:
      - auth1
      - auth2
      - auth3
      - provider1
      - provider2

  auth1:
    restart: unless-stopped
    image: katzenpost/voting_authority
    volumes:
      - ./conf/auth1:/conf
    command: /go/bin/voting -f /conf/authority.toml
    network_mode: host

  auth2:
    restart: unless-stopped
    image: katzenpost/voting_authority
    volumes:
      - ./conf/auth2:/conf
    command: /go/bin/voting -f /conf/authority.toml
    network_mode: host

  auth3:
    restart: unless-stopped
    image: katzenpost/voting_authority
    volumes:
      - ./conf/auth3:/conf
    command: /go/bin/voting -f /conf/authority.toml
    network_mode: host
