version: "2"

services:
  provider1:
    restart: unless-stopped
    image: katzenpost/server
    volumes:
      - ./conf/provider1:/conf
    command: /go/bin/server -f /conf/katzenpost.toml
    ports:
      - "127.0.0.1:59484:59484"
      - "127.0.0.1:36968:36968"
    depends_on:
      - auth1
      - auth2
      - auth3
    networks:
      testing_net:
        ipv4_address: 172.28.1.3

  provider2:
    restart: unless-stopped
    image: katzenpost/server
    volumes:
      - ./conf/provider2:/conf
    command: /go/bin/server -f /conf/katzenpost.toml
    ports:
      - "127.0.0.1:29484:29484"
      - "127.0.0.1:36967:36967"
    depends_on:
      - auth1
      - auth2
      - auth3
      - provider1
    networks:
      testing_net:
        ipv4_address: 172.28.1.4

  mix1:
    restart: unless-stopped
    image: katzenpost/server
    volumes:
      - ./conf/mix1:/conf
    command: /go/bin/server -f /conf/katzenpost.toml
    depends_on:
      - auth1
      - auth2
      - auth3
      - provider1
      - provider2
    networks:
      testing_net:
        ipv4_address: 172.28.1.5

  mix2:
    restart: unless-stopped
    image: katzenpost/server
    volumes:
      - ./conf/mix2:/conf
    command: /go/bin/server -f /conf/katzenpost.toml
    depends_on:
      - auth1
      - auth2
      - auth3
      - provider1
      - provider2
    networks:
      testing_net:
        ipv4_address: 172.28.1.6

  mix3:
    restart: unless-stopped
    image: katzenpost/server
    volumes:
      - ./conf/mix3:/conf
    command: /go/bin/server -f /conf/katzenpost.toml
    depends_on:
      - auth1
      - auth2
      - auth3
      - provider1
      - provider2
    networks:
      testing_net:
        ipv4_address: 172.28.1.7

  auth1:
    restart: unless-stopped
    image: katzenpost/voting_authority
    volumes:
      - ./conf/auth1:/conf
    command: /go/bin/voting -f /conf/authority.toml
    ports:
      - "127.0.0.1:21483:21483"
    networks:
      testing_net:
        ipv4_address: 172.28.1.10
  auth2:
    restart: unless-stopped
    image: katzenpost/voting_authority
    volumes:
      - ./conf/auth2:/conf
    command: /go/bin/voting -f /conf/authority.toml
    ports:
      - "127.0.0.1:22483:22483"
    networks:
      testing_net:
        ipv4_address: 172.28.1.8
  auth3:
    restart: unless-stopped
    image: katzenpost/voting_authority
    volumes:
      - ./conf/auth3:/conf
    command: /go/bin/voting -f /conf/authority.toml
    ports:
      - "127.0.0.1:23483:23483"
    networks:
      testing_net:
        ipv4_address: 172.28.1.9

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
