
services:

  gateway1:
    restart: "no"
    image: katzenpost-go_mod
    volumes:
      - ./:/voting_mixnet
    command: /voting_mixnet/server -f /voting_mixnet/gateway1/katzenpost.toml
    network_mode: host

    depends_on:
      - auth1
      - auth2
      - auth3
  servicenode1:
    restart: "no"
    image: katzenpost-go_mod
    volumes:
      - ./:/voting_mixnet
    command: /voting_mixnet/server -f /voting_mixnet/servicenode1/katzenpost.toml
    network_mode: host

    depends_on:
      - auth1
      - auth2
      - auth3
  mix1:
    restart: "no"
    image: katzenpost-go_mod
    volumes:
      - ./:/voting_mixnet
    command: /voting_mixnet/server -f /voting_mixnet/mix1/katzenpost.toml
    network_mode: host
    depends_on:
      - auth1
      - auth2
      - auth3
  mix2:
    restart: "no"
    image: katzenpost-go_mod
    volumes:
      - ./:/voting_mixnet
    command: /voting_mixnet/server -f /voting_mixnet/mix2/katzenpost.toml
    network_mode: host
    depends_on:
      - auth1
      - auth2
      - auth3
  mix3:
    restart: "no"
    image: katzenpost-go_mod
    volumes:
      - ./:/voting_mixnet
    command: /voting_mixnet/server -f /voting_mixnet/mix3/katzenpost.toml
    network_mode: host
    depends_on:
      - auth1
      - auth2
      - auth3
  replica1:
    restart: "no"
    image: katzenpost-go_mod
    volumes:
      - ./:/voting_mixnet
    command: /voting_mixnet/replica -f /voting_mixnet/replica1/replica.toml
    network_mode: host
    depends_on:
      - auth1
      - auth2
      - auth3
  replica2:
    restart: "no"
    image: katzenpost-go_mod
    volumes:
      - ./:/voting_mixnet
    command: /voting_mixnet/replica -f /voting_mixnet/replica2/replica.toml
    network_mode: host
    depends_on:
      - auth1
      - auth2
      - auth3
  replica3:
    restart: "no"
    image: katzenpost-go_mod
    volumes:
      - ./:/voting_mixnet
    command: /voting_mixnet/replica -f /voting_mixnet/replica3/replica.toml
    network_mode: host
    depends_on:
      - auth1
      - auth2
      - auth3
  replica4:
    restart: "no"
    image: katzenpost-go_mod
    volumes:
      - ./:/voting_mixnet
    command: /voting_mixnet/replica -f /voting_mixnet/replica4/replica.toml
    network_mode: host
    depends_on:
      - auth1
      - auth2
      - auth3
  replica5:
    restart: "no"
    image: katzenpost-go_mod
    volumes:
      - ./:/voting_mixnet
    command: /voting_mixnet/replica -f /voting_mixnet/replica5/replica.toml
    network_mode: host
    depends_on:
      - auth1
      - auth2
      - auth3
  auth1:
    restart: "no"
    image: katzenpost-go_mod
    volumes:
      - ./:/voting_mixnet
    command: /voting_mixnet/dirauth -f /voting_mixnet/auth1/authority.toml
    network_mode: host

  auth2:
    restart: "no"
    image: katzenpost-go_mod
    volumes:
      - ./:/voting_mixnet
    command: /voting_mixnet/dirauth -f /voting_mixnet/auth2/authority.toml
    network_mode: host

  auth3:
    restart: "no"
    image: katzenpost-go_mod
    volumes:
      - ./:/voting_mixnet
    command: /voting_mixnet/dirauth -f /voting_mixnet/auth3/authority.toml
    network_mode: host

  metrics:
    restart: "no"
    image: docker.io/prom/prometheus
    volumes:
      - ./:/voting_mixnet
    command: --config.file="/voting_mixnet/prometheus.yml"
    network_mode: host

  kpclientd:
    restart: "no"
    image: katzenpost-go_mod
    volumes:
      - ./:/voting_mixnet
    command: /voting_mixnet/kpclientd -c /voting_mixnet/client2/client.toml
    network_mode: host
