// Code generated by trunnel. DO NOT EDIT.

//go:build gofuzz
// +build gofuzz

package pigeonhole

func FuzzCachedCourierEnvelope(data []byte) int {
	_, err := ParseCachedCourierEnvelope(data)
	if err != nil {
		return 0
	}
	return 1
}
