// Code generated by trunnel. DO NOT EDIT.

package pigeonhole

import (
	"encoding/binary"
	"errors"
)

type CachedCourierEnvelope struct {
	CacheID              [16]uint8
	IntermediateReplicas [2]uint8
	Dek1                 [60]uint8
	Dek2                 [60]uint8
	ReplyIndex           uint8
	Epoch                uint64
	SenderPubkeyLen      uint16
	SenderPubkey         []uint8
	CiphertextLen        uint32
	Ciphertext           []uint8
}

func (c *CachedCourierEnvelope) Parse(data []byte) ([]byte, error) {
	cur := data
	{
		for idx := 0; idx < 16; idx++ {
			if len(cur) < 1 {
				return nil, errors.New("data too short")
			}
			c.CacheID[idx] = cur[0]
			cur = cur[1:]
		}
	}
	{
		for idx := 0; idx < 2; idx++ {
			if len(cur) < 1 {
				return nil, errors.New("data too short")
			}
			c.IntermediateReplicas[idx] = cur[0]
			cur = cur[1:]
		}
	}
	{
		for idx := 0; idx < 60; idx++ {
			if len(cur) < 1 {
				return nil, errors.New("data too short")
			}
			c.Dek1[idx] = cur[0]
			cur = cur[1:]
		}
	}
	{
		for idx := 0; idx < 60; idx++ {
			if len(cur) < 1 {
				return nil, errors.New("data too short")
			}
			c.Dek2[idx] = cur[0]
			cur = cur[1:]
		}
	}
	{
		if len(cur) < 1 {
			return nil, errors.New("data too short")
		}
		c.ReplyIndex = cur[0]
		cur = cur[1:]
	}
	{
		if len(cur) < 8 {
			return nil, errors.New("data too short")
		}
		c.Epoch = binary.BigEndian.Uint64(cur)
		cur = cur[8:]
	}
	{
		if len(cur) < 2 {
			return nil, errors.New("data too short")
		}
		c.SenderPubkeyLen = binary.BigEndian.Uint16(cur)
		cur = cur[2:]
	}
	{
		c.SenderPubkey = make([]uint8, int(c.SenderPubkeyLen))
		for idx := 0; idx < int(c.SenderPubkeyLen); idx++ {
			if len(cur) < 1 {
				return nil, errors.New("data too short")
			}
			c.SenderPubkey[idx] = cur[0]
			cur = cur[1:]
		}
	}
	{
		if len(cur) < 4 {
			return nil, errors.New("data too short")
		}
		c.CiphertextLen = binary.BigEndian.Uint32(cur)
		cur = cur[4:]
	}
	{
		c.Ciphertext = make([]uint8, int(c.CiphertextLen))
		for idx := 0; idx < int(c.CiphertextLen); idx++ {
			if len(cur) < 1 {
				return nil, errors.New("data too short")
			}
			c.Ciphertext[idx] = cur[0]
			cur = cur[1:]
		}
	}
	return cur, nil
}

func ParseCachedCourierEnvelope(data []byte) (*CachedCourierEnvelope, error) {
	c := new(CachedCourierEnvelope)
	_, err := c.Parse(data)
	if err != nil {
		return nil, err
	}
	return c, nil
}

func (c *CachedCourierEnvelope) encodeBinary() []byte {
	var buf []byte
	for idx := 0; idx < 16; idx++ {
		buf = append(buf, byte(c.CacheID[idx]))
	}
	for idx := 0; idx < 2; idx++ {
		buf = append(buf, byte(c.IntermediateReplicas[idx]))
	}
	for idx := 0; idx < 60; idx++ {
		buf = append(buf, byte(c.Dek1[idx]))
	}
	for idx := 0; idx < 60; idx++ {
		buf = append(buf, byte(c.Dek2[idx]))
	}
	buf = append(buf, byte(c.ReplyIndex))
	{
		tmp := make([]byte, 8)
		binary.BigEndian.PutUint64(tmp, c.Epoch)
		buf = append(buf, tmp...)
	}
	{
		tmp := make([]byte, 2)
		binary.BigEndian.PutUint16(tmp, c.SenderPubkeyLen)
		buf = append(buf, tmp...)
	}
	for idx := 0; idx < int(c.SenderPubkeyLen); idx++ {
		buf = append(buf, byte(c.SenderPubkey[idx]))
	}
	{
		tmp := make([]byte, 4)
		binary.BigEndian.PutUint32(tmp, c.CiphertextLen)
		buf = append(buf, tmp...)
	}
	for idx := 0; idx < int(c.CiphertextLen); idx++ {
		buf = append(buf, byte(c.Ciphertext[idx]))
	}
	return buf
}

func (c *CachedCourierEnvelope) MarshalBinary() ([]byte, error) {
	if err := c.validate(); err != nil {
		return nil, err
	}
	return c.encodeBinary(), nil
}

func (c *CachedCourierEnvelope) validate() error {
	if len(c.CacheID) != 16 {
		return errors.New("array length constraint violated")
	}
	for idx := 0; idx < len(c.CacheID); idx++ {
	}
	if len(c.IntermediateReplicas) != 2 {
		return errors.New("array length constraint violated")
	}
	for idx := 0; idx < len(c.IntermediateReplicas); idx++ {
	}
	if len(c.Dek1) != 60 {
		return errors.New("array length constraint violated")
	}
	for idx := 0; idx < len(c.Dek1); idx++ {
	}
	if len(c.Dek2) != 60 {
		return errors.New("array length constraint violated")
	}
	for idx := 0; idx < len(c.Dek2); idx++ {
	}
	if len(c.SenderPubkey) != int(c.SenderPubkeyLen) {
		return errors.New("array length constraint violated")
	}
	for idx := 0; idx < len(c.SenderPubkey); idx++ {
	}
	if len(c.Ciphertext) != int(c.CiphertextLen) {
		return errors.New("array length constraint violated")
	}
	for idx := 0; idx < len(c.Ciphertext); idx++ {
	}
	return nil
}
