// SPDX-FileCopyrightText: Copyright (C) 2026 David Stainton
// SPDX-License-Identifier: AGPL-3.0-only

// Package chaos wires per-host pumba chaos parameters into the
// docker-compose mixnet generated by core/genconfig. A single YAML
// document describes the chaos to apply to each container; the apply
// tool launches one sidecar pumba container per host with non-empty
// parameters. Containers without an entry, or with an empty entry, are
// left untouched.
//
// The set of valid hostnames is the same set genconfig writes into
// docker-compose.yml as container_name:
//
//	auth1, auth2, auth3                       (directory authorities)
//	gateway1                                  (gateway / client entry)
//	mix1, mix2, mix3                          (mix routing layers)
//	servicenode1, servicenode2, servicenode3  (service nodes + courier plugins)
//	replica1, replica2, replica3, replica4, replica5  (pigeonhole replicas)
//	kpclientd                                 (client daemon)
//
// metrics, grafana, and pyroscope are deliberately excluded so the
// observability path remains usable while chaos is applied to the
// mixnet under test.
package chaos

import (
	"errors"
	"fmt"
	"os"
	"sort"

	"gopkg.in/yaml.v3"
)

// HostChaos collects every per-host parameter the apply tool knows how
// to pass to pumba. Zero values mean "do not apply this primitive";
// only the populated fields turn into pumba invocations.
//
// Multiple primitives on a single host are realised as multiple pumba
// sidecar containers, each carrying its own qdisc (delay, then loss,
// then corrupt). Pause is mutually exclusive with the others because
// it stops the container outright; if PauseForSec is non-zero, the
// netem primitives on the same host are skipped to avoid racing the
// freeze.
type HostChaos struct {
	// LatencyMs is the one-way egress delay applied via tc netem.
	LatencyMs int `yaml:"latency_ms,omitempty"`

	// JitterMs is the +/- jitter applied around LatencyMs.
	JitterMs int `yaml:"jitter_ms,omitempty"`

	// Distribution is the netem delay distribution. One of
	// uniform, normal, pareto, paretonormal. Defaults to normal.
	Distribution string `yaml:"distribution,omitempty"`

	// CorrelationPct is the optional delay correlation, expressed as
	// an integer percent.
	CorrelationPct int `yaml:"correlation_pct,omitempty"`

	// LossPct is the random packet-loss percent, applied via tc netem
	// loss. A decimal such as 0.5 is half a percent.
	LossPct float64 `yaml:"loss_pct,omitempty"`

	// LossCorrelationPct is the optional loss correlation, percent.
	LossCorrelationPct int `yaml:"loss_correlation_pct,omitempty"`

	// CorruptPct is the random single-bit corruption percent,
	// applied via tc netem corrupt. Use sparingly; very low
	// percentages still surface MAC and signature failure paths.
	CorruptPct float64 `yaml:"corrupt_pct,omitempty"`

	// PauseForSec freezes the container for this many seconds via
	// pumba pause. When non-zero, the netem primitives on the same
	// host are skipped for the duration of this iteration.
	PauseForSec int `yaml:"pause_for_sec,omitempty"`
}

// IsEmpty reports whether a HostChaos asks for any chaos. Empty
// entries are skipped by the apply tool.
func (h HostChaos) IsEmpty() bool {
	return h.LatencyMs == 0 && h.JitterMs == 0 && h.LossPct == 0 &&
		h.CorruptPct == 0 && h.PauseForSec == 0
}

// Config is the top-level chaos configuration document. Duration is
// the wall-clock time every netem primitive runs before pumba's tc
// qdisc self-destructs and the container returns to normal.
type Config struct {
	Duration string               `yaml:"duration,omitempty"`
	Hosts    map[string]HostChaos `yaml:"hosts"`
}

// AllHosts is every container name that genconfig emits and that the
// chaos tool is willing to perturb. metrics, grafana, and pyroscope
// are intentionally absent: they are observability infrastructure for
// the mixnet under test, not parts of the mixnet itself.
var AllHosts = []string{
	"auth1", "auth2", "auth3",
	"gateway1",
	"mix1", "mix2", "mix3",
	"servicenode1", "servicenode2", "servicenode3",
	"replica1", "replica2", "replica3", "replica4", "replica5",
	"kpclientd",
}

// Validate checks that every host name in the config is one the chaos
// tool knows how to address. An unknown name is almost always a typo
// in the YAML and would silently do nothing if we let it through.
func (c *Config) Validate() error {
	if c == nil {
		return errors.New("chaos: nil config")
	}
	known := make(map[string]struct{}, len(AllHosts))
	for _, h := range AllHosts {
		known[h] = struct{}{}
	}
	for name := range c.Hosts {
		if _, ok := known[name]; !ok {
			return fmt.Errorf("chaos: unknown host %q (known: %v)", name, AllHosts)
		}
	}
	return nil
}

// SortedHosts returns the host names in c that have non-empty chaos
// parameters, sorted alphabetically. Sorting makes the apply tool's
// output deterministic across runs, which matters when comparing
// reproducer YAMLs.
func (c *Config) SortedHosts() []string {
	out := make([]string, 0, len(c.Hosts))
	for name, hc := range c.Hosts {
		if hc.IsEmpty() {
			continue
		}
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

// LoadFile parses a chaos YAML document and validates it.
func LoadFile(path string) (*Config, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("chaos: read %s: %w", path, err)
	}
	cfg := new(Config)
	if err := yaml.Unmarshal(b, cfg); err != nil {
		return nil, fmt.Errorf("chaos: parse %s: %w", path, err)
	}
	if err := cfg.Validate(); err != nil {
		return nil, err
	}
	return cfg, nil
}

// DefaultDuration is used when the YAML does not specify a duration.
// pumba's tc qdisc self-destructs after this so a forgotten chaos
// run does not linger across iterations.
const DefaultDuration = "5m"
