ARG BASE_IMAGE=docker.io/alpine:3.21
FROM ${BASE_IMAGE}

ARG TARGETARCH
ARG GO_VERSION=1.26.2

RUN adduser katzenpost --gecos "" --disabled-password

# Install build tools. Go needs a C toolchain (gcc + musl-dev) for the
# cgo components; git is used to fetch Go modules during the docker
# build.
RUN apk update && apk upgrade && \
    apk add gcc musl-dev make pv curl netcat-openbsd \
        bash perl coreutils git

# Install Go
RUN curl -fsSL https://go.dev/dl/go${GO_VERSION}.linux-${TARGETARCH}.tar.gz | tar -C /usr/local -xzf - && \
    ln -s /usr/local/go/bin/go /usr/bin/go && \
    ln -s /usr/local/go/bin/gofmt /usr/bin/gofmt
