image: "golang:1.13"

before_script:
  - mkdir -p /go/src/github.com
  - cp -r /builds/katzenpost /go/src/github.com/katzenpost/
  - cd /builds/katzenpost/core/

test-core:
  script:
    - mkdir -p coverage
    - go test -v -cover -coverprofile cover.out -covermode atomic -race  ./...
    - go tool cover -html=cover.out -o coverage/coverage.html
  artifacts:
    paths:
      - coverage/
