// SPDX-FileCopyrightText: © 2023 David Stainton
// SPDX-License-Identifier: AGPL-3.0-only

package thin

import (
	"fmt"
	"time"

	"github.com/katzenpost/hpqc/bacap"

	cpki "github.com/katzenpost/katzenpost/core/pki"
	"github.com/katzenpost/katzenpost/core/sphinx/constants"
)

// Event is the generic interface for all events sent by the thin client.
//
// Events are sent through channels returned by EventSink() and provide
// asynchronous notification of various client operations and status changes.
// Applications should use type assertions to handle specific event types.
//
// Common event types include:
//   - ConnectionStatusEvent: Connection state changes
//   - MessageReplyEvent: Replies to sent messages
//   - NewDocumentEvent: PKI document updates
//   - Channel operation events (CreateWriteChannelReply, etc.)
type Event interface {
	// String returns a human-readable string representation of the Event.
	String() string
}

// ShutdownEvent is sent when the client daemon is shutting down.
//
// This event indicates that the daemon is terminating and the thin client
// connection will be lost. Applications should handle this event by
// performing cleanup and potentially attempting to reconnect.
type ShutdownEvent struct{}

// String returns a string representation of the ShutdownEvent.
func (e *ShutdownEvent) String() string {
	return "ShutdownEvent"
}

// DaemonDisconnectedEvent is emitted when the thin client loses its connection
// to the client daemon. The thin client will automatically attempt to reconnect.
type DaemonDisconnectedEvent struct {
	// IsGraceful is true if the daemon sent a ShutdownEvent before disconnecting.
	// False means the connection was lost unexpectedly (crash, network issue).
	IsGraceful bool

	// Err contains the underlying error that caused the disconnect, if any.
	Err error
}

// String returns a string representation of the DaemonDisconnectedEvent.
func (e *DaemonDisconnectedEvent) String() string {
	if e.IsGraceful {
		return "DaemonDisconnected: graceful shutdown"
	}
	return fmt.Sprintf("DaemonDisconnected: unexpected (err=%v)", e.Err)
}

// ConnectionStatusEvent is sent when the daemon's connection status changes.
//
// This event indicates whether the client daemon is currently connected to
// the mixnet infrastructure. When IsConnected is false, the client operates
// in "offline mode" where channel preparation operations work but actual
// message transmission will fail.
//
// Applications can use this event to:
//   - Display connection status to users
//   - Queue operations for later transmission when offline
//   - Implement retry logic for failed operations
type ConnectionStatusEvent struct {
	// IsConnected indicates whether the daemon is connected to the mixnet.
	// When true, full functionality is available. When false, only offline
	// operations (channel preparation) will work.
	IsConnected bool `cbor:"is_connected"`

	// Err contains any error that caused a disconnection. This field is
	// nil when IsConnected is true or when the disconnection was intentional.
	Err error `cbor:"err"`

	// InstanceToken is a random token generated by the daemon on startup.
	// It uniquely identifies a daemon instance, allowing thin clients to
	// detect whether a reconnect is to the same or a new daemon instance.
	InstanceToken [16]byte `cbor:"instance_token"`
}

// String returns a string representation of the ConnectionStatusEvent.
func (e *ConnectionStatusEvent) String() string {
	if !e.IsConnected {
		return fmt.Sprintf("ConnectionStatus: %v (%v)", e.IsConnected, e.Err)
	}
	return fmt.Sprintf("ConnectionStatus: %v", e.IsConnected)
}

// MessageReplyEvent is the event sent when a new message is received.
type MessageReplyEvent struct {
	// MessageID is the unique identifier for the request associated with the
	// reply.
	MessageID *[MessageIDLength]byte `cbor:"message_id"`

	// SURBID must be a unique identity for each request.
	// This field should be nil if WithSURB is false.
	SURBID *[constants.SURBIDLength]byte `cbor:"surbid"`

	// Payload is the reply payload if any.
	Payload []byte `cbor:"payload"`

	// ReplyIndex is the index of the reply that was actually used when processing
	// this message. This is particularly relevant for pigeonhole channel reads.
	ReplyIndex *uint8 `cbor:"reply_index,omitempty"`

	// ErrorCode indicates the success or failure of the message operation.
	// A value of ThinClientSuccess (0) indicates no error occurred.
	// Non-zero values indicate specific error conditions.
	ErrorCode uint8 `cbor:"error_code"`
}

// String returns a string representation of the MessageReplyEvent.
func (e *MessageReplyEvent) String() string {
	replyIndexStr := ""
	if e.ReplyIndex != nil {
		replyIndexStr = fmt.Sprintf(" replyIndex=%d", *e.ReplyIndex)
	}
	if e.ErrorCode != ThinClientSuccess {
		return fmt.Sprintf("MessageReply: %x %s failed: %s", e.MessageID[:], replyIndexStr, ThinClientErrorToString(e.ErrorCode))
	}
	return fmt.Sprintf("KaetzchenReply: %x %s (%v bytes)", e.MessageID[:], replyIndexStr, len(e.Payload))
}

// MessageSentEvent is the event sent when a message has been fully transmitted.
type MessageSentEvent struct {
	// MessageID is the local unique identifier for the message, generated
	// when the message was enqueued.
	MessageID *[MessageIDLength]byte `cbor:"message_id"`

	// SURBID must be a unique identity for each request.
	// This field should be nil if WithSURB is false.
	SURBID *[constants.SURBIDLength]byte `cbor:"surbid"`

	// SentAt contains the time the message was sent.
	SentAt time.Time `cbor:"sent_at"`

	// ReplyETA is the expected round trip time to receive a response.
	ReplyETA time.Duration `cbor:"reply_eta"`

	// Err is the error message if any error was encountered when sending the message.
	// Empty string indicates no error occurred.
	Err string `cbor:"err,omitempty"`
}

// String returns a string representation of a MessageSentEvent.
func (e *MessageSentEvent) String() string {
	if e.Err != "" {
		return fmt.Sprintf("MessageSent: %x failed: %v", e.MessageID[:], e.Err)
	}
	return fmt.Sprintf("MessageSent: %x", e.MessageID[:])
}

// MessageIDGarbageCollected is the event used to signal when a given
// message ID has been garbage collected.
type MessageIDGarbageCollected struct {
	// MessageID is the local unique identifier for the message.
	MessageID *[MessageIDLength]byte `cbor:"message_id"`
}

// String returns a string representation of a MessageIDGarbageCollected.
func (e *MessageIDGarbageCollected) String() string {
	return fmt.Sprintf("MessageIDGarbageCollected: %x", e.MessageID[:])
}

// NewDocumentEvent is the new document event, signaling that
// we have received a new document from the PKI.
type NewDocumentEvent struct {
	Document *cpki.Document `cbor:"document"`
}

// String returns a string representation of a NewDocumentEvent.
func (e *NewDocumentEvent) String() string {
	return fmt.Sprintf("PKI Document for epoch %d", e.Document.Epoch)
}

// NewPKIDocumentEvent is the unix domain socket protocol message used
// by the daemon to tell the thin client about new PKI document events.
// The payload field contains a CBOR encoded PKI document, stripped of signatures.
type NewPKIDocumentEvent struct {
	Payload []byte `cbor:"payload"`
}

// String returns a string representation of a NewDocumentEvent.
func (e *NewPKIDocumentEvent) String() string {
	doc, err := cpki.ParseDocument(e.Payload)
	if err != nil {
		panic(err)
	}
	return fmt.Sprintf("PKI Document for epoch %d", doc.Epoch)
}

// New Pigeonhole API:

// NewKeypairReply is the reply to a NewKeypair request.
type NewKeypairReply struct {
	// QueryID is used for correlating this reply with the NewKeypair request
	QueryID *[QueryIDLength]byte `cbor:"query_id"`
	// WriteCap is the write capability that should be stored for channel
	WriteCap *bacap.WriteCap `cbor:"write_cap"`
	// ReadCap is the read capability that can be shared with others to allow
	// them to read messages from this channel.
	ReadCap *bacap.ReadCap `cbor:"read_cap"`
	// FirstMessageIndex is the first message index that should be used when
	// writing messages to the channel.
	FirstMessageIndex *bacap.MessageBoxIndex `cbor:"first_message_index"`
	// ErrorCode indicates the reason for a failure to create a new keypair if any.
	// Otherwise it is set to zero for success.
	ErrorCode uint8 `cbor:"error_code"`
}

// String returns a string representation of the NewKeypairReply.
func (e *NewKeypairReply) String() string {
	if e.ErrorCode != ThinClientSuccess {
		return fmt.Sprintf("NewKeypairReply (error: %s)", ThinClientErrorToString(e.ErrorCode))
	}
	return "NewKeypairReply: success"
}

// EncryptReadReply is the reply to an EncryptRead request.
type EncryptReadReply struct {
	// QueryID is used for correlating this reply with the EncryptRead request
	QueryID *[QueryIDLength]byte `cbor:"query_id"`

	// MessageCiphertext is the encrypted message ciphertext that should be sent
	// to the Courier service.
	MessageCiphertext []byte `cbor:"message_ciphertext"`

	// EnvelopeDescriptor contains the serialized EnvelopeDescriptor that
	EnvelopeDescriptor []byte `cbor:"envelope_descriptor"`

	// EnvelopeHash is the hash of the CourierEnvelope that was sent to the
	// mixnet and is used to resume the read operation.
	EnvelopeHash *[32]byte `cbor:"envelope_hash"`

	// NextMessageBoxIndex is the next message box index to use for subsequent
	// read operations. This is computed by the daemon using BACAP's NextIndex.
	NextMessageBoxIndex *bacap.MessageBoxIndex `cbor:"next_message_box_index"`

	// ErrorCode indicates the reason for a failure to encrypt the read if any.
	// Otherwise it is set to zero for success.
	ErrorCode uint8 `cbor:"error_code"`
}

// String returns a string representation of the EncryptReadReply.
func (e *EncryptReadReply) String() string {
	if e.ErrorCode != ThinClientSuccess {
		return fmt.Sprintf("EncryptReadReply (error: %s)", ThinClientErrorToString(e.ErrorCode))
	}
	return fmt.Sprintf("EncryptReadReply: %d bytes ciphertext", len(e.MessageCiphertext))
}

// EncryptWriteReply is the reply to an EncryptWrite request.
type EncryptWriteReply struct {
	// QueryID is used for correlating this reply with the EncryptWrite request
	QueryID *[QueryIDLength]byte `cbor:"query_id"`

	// MessageCiphertext is the encrypted message ciphertext that should be sent
	// to the Courier service.
	MessageCiphertext []byte `cbor:"message_ciphertext"`

	// EnvelopeDescriptor contains the serialized EnvelopeDescriptor that
	// contains the private key material needed to decrypt the envelope reply.
	EnvelopeDescriptor []byte `cbor:"envelope_descriptor"`

	// EnvelopeHash is the hash of the CourierEnvelope that was sent to the
	// mixnet and is used to resume the write operation.
	EnvelopeHash *[32]byte `cbor:"envelope_hash"`

	// NextMessageBoxIndex is the next message box index to use for subsequent
	// write operations. This is computed by the daemon using BACAP's NextIndex.
	NextMessageBoxIndex *bacap.MessageBoxIndex `cbor:"next_message_box_index"`

	// ErrorCode indicates the reason for a failure to encrypt the write if any.
	// Otherwise it is set to zero for success.
	ErrorCode uint8 `cbor:"error_code"`
}

// String returns a string representation of the EncryptWriteReply.
func (e *EncryptWriteReply) String() string {
	if e.ErrorCode != ThinClientSuccess {
		return fmt.Sprintf("EncryptWriteReply (error: %s)", ThinClientErrorToString(e.ErrorCode))
	}
	return fmt.Sprintf("EncryptWriteReply: %d bytes ciphertext", len(e.MessageCiphertext))
}

// StartResendingEncryptedMessageReply is the reply to a StartResendingEncryptedMessage request.
type StartResendingEncryptedMessageReply struct {

	// QueryID is used for correlating this reply with the StartResendingEncryptedMessage request
	QueryID *[QueryIDLength]byte `cbor:"query_id"`

	// Plaintext is the plaintext message that was read from the channel.
	Plaintext []byte `cbor:"plaintext"`

	// ErrorCode indicates the reason for a failure to start resending the encrypted message if any.
	// Otherwise it is set to zero for success.
	ErrorCode uint8 `cbor:"error_code"`

	// CourierIdentityHash is the 32-byte hash of the identity key of the courier that was
	// selected to handle this message. Callers can watch PKI document updates for this
	// courier disappearing from consensus and cancel+re-encrypt if it does.
	CourierIdentityHash *[32]byte `cbor:"courier_identity_hash"`

	// CourierQueueID is the queue ID of the courier that was selected.
	CourierQueueID []byte `cbor:"courier_queue_id"`
}

// String returns a string representation of the StartResendingEncryptedMessageReply.
func (e *StartResendingEncryptedMessageReply) String() string {
	if e.ErrorCode != ThinClientSuccess {
		return fmt.Sprintf("StartResendingEncryptedMessageReply (error: %s)", ThinClientErrorToString(e.ErrorCode))
	}
	return fmt.Sprintf("StartResendingEncryptedMessageReply: %d bytes plaintext, courier=%x", len(e.Plaintext), e.CourierIdentityHash)
}

// CancelResendingEncryptedMessageReply is the reply to a CancelResendingEncryptedMessage request.
type CancelResendingEncryptedMessageReply struct {
	// QueryID is used for correlating this reply with the CancelResendingEncryptedMessage request
	QueryID *[QueryIDLength]byte `cbor:"query_id"`

	// ErrorCode indicates the reason for a failure to cancel resending the encrypted message if any.
	// Otherwise it is set to zero for success.
	ErrorCode uint8 `cbor:"error_code"`
}

// String returns a string representation of the CancelResendingEncryptedMessageReply.
func (e *CancelResendingEncryptedMessageReply) String() string {
	if e.ErrorCode != ThinClientSuccess {
		return fmt.Sprintf("CancelResendingEncryptedMessageReply (error: %s)", ThinClientErrorToString(e.ErrorCode))
	}
	return "CancelResendingEncryptedMessageReply: success"
}

// StartResendingCopyCommandReply is the reply to a StartResendingCopyCommand request.
type StartResendingCopyCommandReply struct {
	// QueryID is used for correlating this reply with the StartResendingCopyCommand request
	QueryID *[QueryIDLength]byte `cbor:"query_id"`

	// ErrorCode indicates the reason for a failure to execute the copy command if any.
	// Otherwise it is set to zero for success.
	ErrorCode uint8 `cbor:"error_code"`
}

// String returns a string representation of the StartResendingCopyCommandReply.
func (e *StartResendingCopyCommandReply) String() string {
	if e.ErrorCode != ThinClientSuccess {
		return fmt.Sprintf("StartResendingCopyCommandReply (error: %s)", ThinClientErrorToString(e.ErrorCode))
	}
	return "StartResendingCopyCommandReply: success"
}

// CancelResendingCopyCommandReply is the reply to a CancelResendingCopyCommand request.
type CancelResendingCopyCommandReply struct {
	// QueryID is used for correlating this reply with the CancelResendingCopyCommand request
	QueryID *[QueryIDLength]byte `cbor:"query_id"`

	// ErrorCode indicates the reason for a failure to cancel the copy command if any.
	// Otherwise it is set to zero for success.
	ErrorCode uint8 `cbor:"error_code"`
}

// String returns a string representation of the CancelResendingCopyCommandReply.
func (e *CancelResendingCopyCommandReply) String() string {
	if e.ErrorCode != ThinClientSuccess {
		return fmt.Sprintf("CancelResendingCopyCommandReply (error: %s)", ThinClientErrorToString(e.ErrorCode))
	}
	return "CancelResendingCopyCommandReply: success"
}

// NextMessageBoxIndexReply is the reply to a NextMessageBoxIndex request.
type NextMessageBoxIndexReply struct {
	// QueryID is used for correlating this reply with the NextMessageBoxIndex request
	QueryID *[QueryIDLength]byte `cbor:"query_id"`

	// NextMessageBoxIndex is the incremented message box index.
	NextMessageBoxIndex *bacap.MessageBoxIndex `cbor:"next_message_box_index"`

	// ErrorCode indicates the reason for a failure to increment the index if any.
	// Otherwise it is set to zero for success.
	ErrorCode uint8 `cbor:"error_code"`
}

// String returns a string representation of the NextMessageBoxIndexReply.
func (e *NextMessageBoxIndexReply) String() string {
	if e.ErrorCode != ThinClientSuccess {
		return fmt.Sprintf("NextMessageBoxIndexReply (error: %s)", ThinClientErrorToString(e.ErrorCode))
	}
	return "NextMessageBoxIndexReply: success"
}

// Copy Channel API:

// CreateCourierEnvelopesFromPayloadReply is sent in response to a CreateCourierEnvelopesFromPayload request.
// It provides multiple serialized CopyStreamElements, one for each chunk of the payload.
type CreateCourierEnvelopesFromPayloadReply struct {
	// QueryID is used for correlating this reply with the CreateCourierEnvelopesFromPayload request
	// that created it.
	QueryID *[QueryIDLength]byte `cbor:"query_id"`

	// Envelopes is a slice of serialized CopyStreamElements, one per chunk.
	Envelopes [][]byte `cbor:"envelopes"`

	// NextDestIndex is the next destination message box index after all boxes
	// consumed by this call. Use this as DestStartIndex in subsequent calls
	// to continue writing to the same destination stream.
	NextDestIndex *bacap.MessageBoxIndex `cbor:"next_dest_index"`

	// ErrorCode indicates the success or failure of the envelope creation.
	// A value of ThinClientSuccess indicates successful creation.
	ErrorCode uint8 `cbor:"error_code"`
}

// String returns a string representation of the CreateCourierEnvelopesFromPayloadReply.
func (e *CreateCourierEnvelopesFromPayloadReply) String() string {
	if e.ErrorCode != ThinClientSuccess {
		return fmt.Sprintf("CreateCourierEnvelopesFromPayloadReply: queryID=%x (error: %s)", e.QueryID[:], ThinClientErrorToString(e.ErrorCode))
	}
	return fmt.Sprintf("CreateCourierEnvelopesFromPayloadReply: queryID=%x numEnvelopes=%d", e.QueryID[:], len(e.Envelopes))
}

// CreateCourierEnvelopesFromPayloadsReply is sent in response to a CreateCourierEnvelopesFromPayloads request.
// It provides multiple serialized CopyStreamElements packed efficiently from multiple destination payloads.
type CreateCourierEnvelopesFromPayloadsReply struct {
	// QueryID is used for correlating this reply with the CreateCourierEnvelopesFromPayloads request
	// that created it.
	QueryID *[QueryIDLength]byte `cbor:"query_id"`

	// Envelopes is a slice of serialized CopyStreamElements containing all the courier envelopes
	// from all destinations packed efficiently together.
	Envelopes [][]byte `cbor:"envelopes"`

	// Buffer contains any data buffered by the encoder that hasn't been output yet.
	// This can be persisted for crash recovery and restored via SetStreamBuffer.
	Buffer []byte `cbor:"buffer"`

	// NextDestIndices contains the next destination message box index for each
	// destination, in the same order as the destinations in the request.
	// Use these as StartIndex in subsequent calls to continue writing to the
	// same destination streams.
	NextDestIndices []*bacap.MessageBoxIndex `cbor:"next_dest_indices"`

	// ErrorCode indicates the success or failure of the envelope creation.
	// A value of ThinClientSuccess indicates successful creation.
	ErrorCode uint8 `cbor:"error_code"`
}

// String returns a string representation of the CreateCourierEnvelopesFromPayloadsReply.
func (e *CreateCourierEnvelopesFromPayloadsReply) String() string {
	if e.ErrorCode != ThinClientSuccess {
		return fmt.Sprintf("CreateCourierEnvelopesFromPayloadsReply: queryID=%x (error: %s)", e.QueryID[:], ThinClientErrorToString(e.ErrorCode))
	}
	return fmt.Sprintf("CreateCourierEnvelopesFromPayloadsReply: queryID=%x numEnvelopes=%d bufferLen=%d", e.QueryID[:], len(e.Envelopes), len(e.Buffer))
}

// SetStreamBufferReply is sent in response to a SetStreamBuffer request.
// It confirms that the buffer state has been restored for the given stream ID.
type SetStreamBufferReply struct {
	// QueryID is used for correlating this reply with the SetStreamBuffer request.
	QueryID *[QueryIDLength]byte `cbor:"query_id"`

	// ErrorCode indicates the success or failure of the operation.
	ErrorCode uint8 `cbor:"error_code"`
}

// String returns a string representation of the SetStreamBufferReply.
func (e *SetStreamBufferReply) String() string {
	if e.ErrorCode != ThinClientSuccess {
		return fmt.Sprintf("SetStreamBufferReply: queryID=%x (error: %s)", e.QueryID[:], ThinClientErrorToString(e.ErrorCode))
	}
	return fmt.Sprintf("SetStreamBufferReply: queryID=%x success", e.QueryID[:])
}
