
[UpstreamProxy]
  Type = "none"

[Logging]
  Disable = false
  Level = "DEBUG"
  File = "/tmp/ping.log"

[NonvotingAuthority]
    Address = "127.0.0.1:29483"
    PublicKey = "o4w1Nyj/nKNwho5SWfAIfh7SMU8FRx52nMHGgYsMHqQ="

[Debug]
  PollingInterval = 10
  