# node_counts
mix_count: 3
provider_count: 2
dirauth_count: 3

# generate config params
sr: 0
mu: 0.005
muMax: 1000
lP: 0.001
lPMax: 1000
lL: 0.0005
lLMax: 1000
lD: 0.0005
lDMax: 3000
lM: 0.0005
lMMax: 100
UserForwardPayloadLength: 2000
nike: "x25519"
kem: ""
net_name: "voting_mixnet"
#  DEBUG, INFO, NOTICE, WARNING, ERROR, CRITICAL"
log_level: "INFO"
base_port: 30000
# update this to your public IP addresses in all the generated files
bind_addr: "127.0.0.1"
