// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

/*
Package panda is a generated protocol buffer package.

It is generated from these files:
	core.proto

It has these top-level messages:
	KeyExchange
*/
package panda

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KeyExchange_Status int32

const (
	KeyExchange_INIT      KeyExchange_Status = 0
	KeyExchange_EXCHANGE1 KeyExchange_Status = 1
	KeyExchange_EXCHANGE2 KeyExchange_Status = 2
)

var KeyExchange_Status_name = map[int32]string{
	0: "INIT",
	1: "EXCHANGE1",
	2: "EXCHANGE2",
}
var KeyExchange_Status_value = map[string]int32{
	"INIT":      0,
	"EXCHANGE1": 1,
	"EXCHANGE2": 2,
}

func (x KeyExchange_Status) Enum() *KeyExchange_Status {
	p := new(KeyExchange_Status)
	*p = x
	return p
}
func (x KeyExchange_Status) String() string {
	return proto.EnumName(KeyExchange_Status_name, int32(x))
}
func (x *KeyExchange_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(KeyExchange_Status_value, data, "KeyExchange_Status")
	if err != nil {
		return err
	}
	*x = KeyExchange_Status(value)
	return nil
}
func (KeyExchange_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type KeyExchange struct {
	Status           *KeyExchange_Status `protobuf:"varint,1,req,name=status,enum=panda.KeyExchange_Status" json:"status,omitempty"`
	KeyExchangeBytes []byte              `protobuf:"bytes,2,req,name=key_exchange_bytes,json=keyExchangeBytes" json:"key_exchange_bytes,omitempty"`
	SharedSecret     []byte              `protobuf:"bytes,3,opt,name=shared_secret,json=sharedSecret" json:"shared_secret,omitempty"`
	DhPrivate        []byte              `protobuf:"bytes,4,opt,name=dh_private,json=dhPrivate" json:"dh_private,omitempty"`
	Key              []byte              `protobuf:"bytes,5,opt,name=key" json:"key,omitempty"`
	Meeting1         []byte              `protobuf:"bytes,6,opt,name=meeting1" json:"meeting1,omitempty"`
	Meeting2         []byte              `protobuf:"bytes,7,opt,name=meeting2" json:"meeting2,omitempty"`
	Message1         []byte              `protobuf:"bytes,8,opt,name=message1" json:"message1,omitempty"`
	Message2         []byte              `protobuf:"bytes,9,opt,name=message2" json:"message2,omitempty"`
	SharedKey        []byte              `protobuf:"bytes,10,opt,name=shared_key,json=sharedKey" json:"shared_key,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *KeyExchange) Reset()                    { *m = KeyExchange{} }
func (m *KeyExchange) String() string            { return proto.CompactTextString(m) }
func (*KeyExchange) ProtoMessage()               {}
func (*KeyExchange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *KeyExchange) GetStatus() KeyExchange_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return KeyExchange_INIT
}

func (m *KeyExchange) GetKeyExchangeBytes() []byte {
	if m != nil {
		return m.KeyExchangeBytes
	}
	return nil
}

func (m *KeyExchange) GetSharedSecret() []byte {
	if m != nil {
		return m.SharedSecret
	}
	return nil
}

func (m *KeyExchange) GetDhPrivate() []byte {
	if m != nil {
		return m.DhPrivate
	}
	return nil
}

func (m *KeyExchange) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyExchange) GetMeeting1() []byte {
	if m != nil {
		return m.Meeting1
	}
	return nil
}

func (m *KeyExchange) GetMeeting2() []byte {
	if m != nil {
		return m.Meeting2
	}
	return nil
}

func (m *KeyExchange) GetMessage1() []byte {
	if m != nil {
		return m.Message1
	}
	return nil
}

func (m *KeyExchange) GetMessage2() []byte {
	if m != nil {
		return m.Message2
	}
	return nil
}

func (m *KeyExchange) GetSharedKey() []byte {
	if m != nil {
		return m.SharedKey
	}
	return nil
}

func init() {
	proto.RegisterType((*KeyExchange)(nil), "panda.KeyExchange")
	proto.RegisterEnum("panda.KeyExchange_Status", KeyExchange_Status_name, KeyExchange_Status_value)
}

func init() { proto.RegisterFile("core.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0x84, 0x40,
	0x18, 0x86, 0x53, 0x77, 0x4d, 0xbf, 0xdc, 0x90, 0x39, 0x4d, 0x41, 0x20, 0xdb, 0xc5, 0x43, 0x48,
	0xce, 0x3f, 0xa8, 0x90, 0x5a, 0x16, 0x96, 0x70, 0x3b, 0x74, 0x93, 0x49, 0x3f, 0x74, 0x91, 0x54,
	0x9c, 0x29, 0xf2, 0x07, 0xf4, 0xbf, 0xc3, 0x19, 0x2b, 0xf7, 0x36, 0xef, 0xf3, 0xbc, 0x03, 0xef,
	0x0c, 0x40, 0xde, 0xf6, 0x18, 0x75, 0x7d, 0x2b, 0x5b, 0xb2, 0xec, 0x78, 0x53, 0xf0, 0xf5, 0xb7,
	0x05, 0x67, 0x5b, 0x1c, 0x92, 0xaf, 0xbc, 0xe2, 0x4d, 0x89, 0x24, 0x06, 0x5b, 0x48, 0x2e, 0x3f,
	0x04, 0x35, 0x02, 0x33, 0x3c, 0x67, 0x17, 0x91, 0xea, 0x45, 0xb3, 0x4e, 0xb4, 0x57, 0x85, 0x74,
	0x2a, 0x92, 0x1b, 0x20, 0x35, 0x0e, 0x19, 0x4e, 0x3a, 0x7b, 0x1b, 0x24, 0x0a, 0x6a, 0x06, 0x66,
	0xe8, 0xa5, 0x7e, 0xfd, 0x7f, 0xef, 0x7e, 0xe4, 0xe4, 0x1a, 0x56, 0xa2, 0xe2, 0x3d, 0x16, 0x99,
	0xc0, 0xbc, 0x47, 0x49, 0xad, 0xc0, 0x08, 0xbd, 0xd4, 0xd3, 0x70, 0xaf, 0x18, 0xb9, 0x02, 0x28,
	0xaa, 0xac, 0xeb, 0x0f, 0x9f, 0x5c, 0x22, 0x5d, 0xa8, 0x86, 0x5b, 0x54, 0xcf, 0x1a, 0x10, 0x1f,
	0xac, 0x1a, 0x07, 0xba, 0x54, 0x7c, 0x3c, 0x92, 0x4b, 0x70, 0xde, 0x11, 0xe5, 0xa1, 0x29, 0x63,
	0x6a, 0x2b, 0xfc, 0x97, 0x67, 0x8e, 0xd1, 0xd3, 0x23, 0xc7, 0xb4, 0x13, 0x82, 0x97, 0x18, 0x53,
	0xe7, 0xd7, 0xe9, 0x3c, 0x73, 0x8c, 0xba, 0x47, 0x8e, 0x8d, 0x03, 0xa7, 0x57, 0x8c, 0x43, 0x40,
	0x0f, 0xd4, 0x64, 0x8b, 0xc3, 0xfa, 0x16, 0x6c, 0xfd, 0x49, 0xc4, 0x81, 0xc5, 0x66, 0xb7, 0x79,
	0xf1, 0x4f, 0xc8, 0x0a, 0xdc, 0xe4, 0xf5, 0xe1, 0xe9, 0x6e, 0xf7, 0x98, 0xc4, 0xbe, 0x31, 0x8f,
	0xcc, 0x37, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x29, 0xf2, 0xf8, 0x9b, 0x01, 0x00, 0x00,
}
