# SPDX-License-Identifier: AGPL-3.0-only

when:
  - event: [manual, cron]
  - event: pull_request
    branch: main

steps:
  - name: integration
    image: localhost/katzenpost-ci:latest
    commands:
      - make test-integration
