# Katzenpost server configuration file.

#
# The Server section contains mandatory information common to all nodes.
#

[Server]
  Identifier = "provider1"

  # Addresses are the IP address/port combinations that the server will bind
  # to for incoming connections.
  Addresses = [ "172.28.1.3:59484"]

  # DataDir is the absolute path to the server's state files.
  DataDir = "/conf/provider_data"

  # IsProvider specifies if the server is a provider (vs a mix).
  IsProvider = true

#
# The PKI section contains the directory authority configuration.
#

[PKI]
  [PKI.Voting]
  [[PKI.Voting.Peers]]
    Addresses = ["172.28.1.10:29483"]
    IdentityPublicKey = "yftvUNe597+VpB92/D4ZYemFk4k//G3dL+VGJv2oJ30="
    LinkPublicKey = "lS9yYV9TSvIPSHQDFtOkkKJMh/MsjhMx4DB6Sb81vGs="

  [[PKI.Voting.Peers]]
    Addresses = ["172.28.1.8:29483"]
    IdentityPublicKey = "KhB8yGWzyiof/KzoOdzvph8hbm6PVLkDrl0RFtMe+jE="
    LinkPublicKey = "fuJM0f6NVX5dVOPrQSsvO/0HDUEPlP3ZNjt72DgTngE="

  [[PKI.Voting.Peers]]
    Addresses = ["172.28.1.9:29483"]
    IdentityPublicKey = "T7k2iiO4Wxyl9ACCaG1quA7oC8bBZGc2593XSiz19o4="
    LinkPublicKey = "fLtjYvzbUkkVlKDcgmMZz+GEwFFMGt8eBcY8W4RD0HA="

#
# The Logging section controls the logging.
#

[Logging]

  # Disable disables logging entirely.
  Disable = false

  # File specifies the log file, if omitted stdout will be used.
  File = "/conf/provider_data/katzenpost.log"

  # Level specifies the log level out of `ERROR`, `WARNING`, `NOTICE`,
  # `INFO` and `DEBUG`.
  #
  # Warning: The `DEBUG` log level is unsafe for production use.
  Level = "DEBUG"

[Debug]
  DisableRateLimit = true

#
# The Provider secton specifies the Provider configuration.
#

[Provider]
EnableUserRegistrationHTTP = true
UserRegistrationHTTPAddresses = ["172.28.1.3:36968"]
AdvertiseUserRegistrationHTTPAddresses = ["http://127.0.0.1:36968"]

[[Provider.Kaetzchen]]
    Disable = false
    Capability = "loop"
    Endpoint = "+loop"

   [[Provider.CBORPluginKaetzchen]]
     Disable = false
     Capability = "panda"
     Endpoint = "+panda"
     Command = "/go/bin/panda_server"
     MaxConcurrency = 1
     [Provider.CBORPluginKaetzchen.Config]
      log_dir = "/conf/service_logs"
      log_level = "DEBUG"
      fileStore = "/conf/service_data/panda.storage"

  [[Provider.CBORPluginKaetzchen]]
    Disable = false
    Capability = "spool"
    Endpoint = "+spool"
    Command = "/go/bin/memspool"
    MaxConcurrency = 1
    [Provider.CBORPluginKaetzchen.Config]
      data_store = "/conf/service_data/memspool.storage"
      log_dir = "/conf/service_logs"

#
# The Management section specifies the management interface configuration.
#

[Management]

  # Enable enables the management interface.
  Enable = false
